// Core Grafana history https://github.com/grafana/grafana/blob/v11.0.0-preview/public/app/plugins/datasource/prometheus/components/monaco-query-field/monaco-completion-provider/index.ts
import { type TimeRange } from '@grafana/data';
import type { Monaco, monacoTypes } from '@grafana/ui';

import { type Completion, type CompletionType, getCompletions } from './completions';
import { type DataProvider } from './data_provider';
import { getSituation } from './situation';
import { NeverCaseError } from './util';

export type TriggerType = 'partial' | 'full';

export type MonacoQueryFieldLocalState = {
  isManualTriggerRequested: boolean;
};

const TRIGGER_CHARACTERS = ['{', ',', '[', '(', '=', '~', ' ', '"'];
const MIN_WORD_LENGTH_FOR_FULL_COMPLETIONS = 3;

export function getSuggestOptions(): monacoTypes.editor.ISuggestOptions {
  return {
    // monaco-editor sometimes provides suggestions automatically, i am not
    // sure based on what, seems to be by analyzing the words already
    // written.
    // to try it out:
    // - enter `go_goroutines{job~`
    // - have the cursor at the end of the string
    // - press ctrl-enter
    // - you will get two suggestions
    // those were not provided by grafana, they are offered automatically.
    // i want to remove those. the only way i found is:
    // - every suggestion-item has a `kind` attribute,
    //   that controls the icon to the left of the suggestion.
    // - items auto-generated by monaco have `kind` set to `text`.
    // - we make sure grafana-provided suggestions do not have `kind` set to `text`.
    // - and then we tell monaco not to show suggestions of kind `text`
    showWords: false,
  };
}

function getMonacoCompletionItemKind(type: CompletionType, monaco: Monaco): monacoTypes.languages.CompletionItemKind {
  switch (type) {
    case 'KEYWORD':
      return monaco.languages.CompletionItemKind.Keyword;
    case 'DURATION':
      return monaco.languages.CompletionItemKind.Unit;
    case 'FUNCTION':
      return monaco.languages.CompletionItemKind.Variable;
    case 'HISTORY':
      return monaco.languages.CompletionItemKind.Snippet;
    case 'LABEL_NAME':
      return monaco.languages.CompletionItemKind.Enum;
    case 'LABEL_VALUE':
      return monaco.languages.CompletionItemKind.EnumMember;
    case 'METRIC_NAME':
      return monaco.languages.CompletionItemKind.Constructor;
    default:
      throw new NeverCaseError(type);
  }
}

function getTriggerType(
  word: monacoTypes.editor.IWordAtPosition | null,
  model: monacoTypes.editor.ITextModel,
  position: monacoTypes.Position,
  state: MonacoQueryFieldLocalState
): TriggerType {
  // Manual trigger (Ctrl+Space) - always full completions
  if (state.isManualTriggerRequested) {
    return 'full';
  }

  const charBeforeCursor = model.getValueInRange({
    startLineNumber: position.lineNumber,
    endLineNumber: position.lineNumber,
    startColumn: Math.max(1, position.column - 1),
    endColumn: position.column,
  });

  if (TRIGGER_CHARACTERS.includes(charBeforeCursor)) {
    return 'full';
  }

  // For typed words of sufficient length, use full completions
  if (word && word.word.length >= MIN_WORD_LENGTH_FOR_FULL_COMPLETIONS) {
    return 'full';
  }

  return 'partial';
}

export function getCompletionProvider(
  monaco: Monaco,
  dataProvider: DataProvider,
  timeRange: TimeRange,
  triggerSuggestions?: () => void
): {
  provider: monacoTypes.languages.CompletionItemProvider;
  state: MonacoQueryFieldLocalState;
  dispose: () => void;
} {
  const state: MonacoQueryFieldLocalState = {
    isManualTriggerRequested: false,
  };
  let activeRequestId = 0;
  let activeRequestIdentity: string | undefined;
  let latestItems: Completion[] = [];
  let hasProgress = false;
  let isComplete = false;
  let disposed = false;

  const toCompletionList = (
    items: Completion[],
    range: monacoTypes.IRange,
    incomplete: boolean
  ): monacoTypes.languages.CompletionList => {
    const suggestions: monacoTypes.languages.CompletionItem[] = items.map((item, index) => ({
      kind: getMonacoCompletionItemKind(item.type, monaco),
      label: item.label,
      insertText: item.insertText,
      insertTextRules: item.insertTextRules,
      detail: item.detail,
      documentation: item.documentation,
      sortText: index.toString().padStart(6, '0'),
      range,
      command: item.triggerOnInsert
        ? {
            id: 'editor.action.triggerSuggest',
            title: '',
          }
        : undefined,
    }));

    return { suggestions, incomplete };
  };

  const provideCompletionItems = (
    model: monacoTypes.editor.ITextModel,
    position: monacoTypes.Position
  ): monacoTypes.languages.ProviderResult<monacoTypes.languages.CompletionList> => {
    const word = model.getWordAtPosition(position);
    const range =
      word != null
        ? monaco.Range.lift({
            startLineNumber: position.lineNumber,
            endLineNumber: position.lineNumber,
            startColumn: word.startColumn,
            endColumn: word.endColumn,
          })
        : monaco.Range.fromPositions(position);

    // Get adjusted position for cursor/selection handling
    const adjustedPosition = getAdjustedPosition(position);
    const offset = model.getOffsetAt(adjustedPosition);
    const situation = getSituation(model.getValue(), offset);

    // Early exit if no situation detected
    if (situation === null) {
      return Promise.resolve({ suggestions: [], incomplete: false });
    }

    const triggerType: TriggerType = getTriggerType(word, model, position, state);
    const requestIdentity = [
      model.id,
      model.getValue(),
      position.lineNumber,
      position.column,
      JSON.stringify(situation),
    ].join(':');
    // Ctrl+Space clears isManualTriggerRequested after 300ms. Later batches
    // retrigger with triggerType "partial" for short/empty words. Reuse the
    // in-flight full request instead of replacing it with functions only.
    if (triggerSuggestions && requestIdentity === activeRequestIdentity && (hasProgress || isComplete)) {
      return Promise.resolve(toCompletionList(latestItems, range, !isComplete));
    }

    const requestId = ++activeRequestId;
    activeRequestIdentity = requestIdentity;
    latestItems = [];
    hasProgress = false;
    isComplete = false;

    let resolveFirstProgress: (items: Completion[]) => void;
    const firstProgress = new Promise<Completion[]>((resolve) => {
      resolveFirstProgress = resolve;
    });

    const publishProgress = (items: Completion[]) => {
      if (disposed || requestId !== activeRequestId) {
        return;
      }
      latestItems = items;
      if (!hasProgress) {
        hasProgress = true;
        resolveFirstProgress(items);
      } else {
        triggerSuggestions?.();
      }
    };
    const completionRequest = triggerSuggestions
      ? getCompletions(situation, dataProvider, timeRange, word?.word, triggerType, publishProgress)
      : getCompletions(situation, dataProvider, timeRange, word?.word, triggerType);

    const finalItems = completionRequest.then((items) => {
      if (!disposed && requestId === activeRequestId) {
        latestItems = items;
        isComplete = true;
        if (hasProgress) {
          triggerSuggestions?.();
        }
      }
      return items;
    });

    return Promise.race([firstProgress, finalItems]).then((items) => {
      if (disposed || requestId !== activeRequestId) {
        return { suggestions: [], incomplete: false };
      }
      return toCompletionList(items, range, !isComplete);
    });
  };

  // Helper function to handle position adjustment for selection
  function getAdjustedPosition(position: monacoTypes.Position): { column: number; lineNumber: number } {
    let adjustedColumn = position.column;

    // Check to see if the browser supports window.getSelection()
    if (window.getSelection) {
      const selectedText = window.getSelection()?.toString();
      // If the user has selected text, adjust the cursor position to be at the start of the selection
      if (selectedText && selectedText.length > 0) {
        adjustedColumn = Math.max(1, adjustedColumn - selectedText.length);
      }
    }

    return {
      column: adjustedColumn,
      lineNumber: position.lineNumber,
    };
  }

  return {
    provider: {
      triggerCharacters: TRIGGER_CHARACTERS,
      provideCompletionItems,
    },
    state,
    dispose: () => {
      disposed = true;
      activeRequestId++;
      activeRequestIdentity = undefined;
      latestItems = [];
    },
  };
}
